name: chat_connect_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.5

  
  #State
  flutter_bloc: ^8.1.4

  #Core
  equatable: ^2.0.5
  image_picker: ^1.0.7
  app_settings: ^5.1.1
  permission_handler: ^11.2.0
  easy_localization: ^3.0.3
  kartal: ^3.5.0
  regexpattern: ^2.6.0
  logger: ^2.0.2+1
  easy_logger: ^0.0.2

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_preview: ^1.1.0

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
