// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaexPkUZj8UqQ-RXTDuXewfSuQ6oa5Gw',
    appId: '1:1045667322083:web:37850e981e95d4f4f10dd6',
    messagingSenderId: '1045667322083',
    projectId: 'chatconnectapp-bf24d',
    authDomain: 'chatconnectapp-bf24d.firebaseapp.com',
    storageBucket: 'chatconnectapp-bf24d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxYftZ6i_Uzu-nboPXf0i_pz3d6DiHHQ',
    appId: '1:1045667322083:android:0b1abb718cf57560f10dd6',
    messagingSenderId: '1045667322083',
    projectId: 'chatconnectapp-bf24d',
    storageBucket: 'chatconnectapp-bf24d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kavtu81L5femHsp-PcZMQ1MXSs--vIM',
    appId: '1:1045667322083:ios:b3212aad148d0183f10dd6',
    messagingSenderId: '1045667322083',
    projectId: 'chatconnectapp-bf24d',
    storageBucket: 'chatconnectapp-bf24d.appspot.com',
    iosBundleId: 'com.example.chatConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kavtu81L5femHsp-PcZMQ1MXSs--vIM',
    appId: '1:1045667322083:ios:38f5d55a2c11437ef10dd6',
    messagingSenderId: '1045667322083',
    projectId: 'chatconnectapp-bf24d',
    storageBucket: 'chatconnectapp-bf24d.appspot.com',
    iosBundleId: 'com.example.chatConnectApp.RunnerTests',
  );
}
